//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

export const LOGOUT_ENABLE_LOADER = 'LOGOUT_ENABLE_LOADER';
export const LOGOUT_DISABLE_LOADER = 'LOGOUT_DISABLE_LOADER';

export const REGISTRATION_ENABLE_LOADER = 'REGISTRATION_ENABLE_LOADER';
export const REGISTRATION_DISABLE_LOADER = 'REGISTRATION_DISABLE_LOADER';

export const ARTICLES_FETCH_ENABLE_LOADER = 'ARTICLES_FETCH_ENABLE_LOADER';
export const ARTICLES_FETCH_DISABLE_LOADER = 'ARTICLES_FETCH_DISABLE_LOADER';

export const RELAXATION_EXERCISES_FETCH_ENABLE_LOADER = 'RELAXATION_EXERCISES_FETCH_ENABLE_LOADER';
export const RELAXATION_EXERCISES_FETCH_DISABLE_LOADER = 'RELAXATION_EXERCISES_FETCH_DISABLE_LOADER';

export const LOCKDOWN_MENTAL_HEALTH_TIPS_FETCH_ENABLE_LOADER = 'LOCKDOWN_MENTAL_HEALTH_TIPS_FETCH_ENABLE_LOADER';
export const LOCKDOWN_MENTAL_HEALTH_TIPS_FETCH_DISABLE_LOADER = 'LOCKDOWN_MENTAL_HEALTH_TIPS_FETCH_DISABLE_LOADER';

export const ARTICLE_FETCH_ENABLE_LOADER = 'ARTICLE_FETCH_ENABLE_LOADER';
export const ARTICLE_FETCH_DISABLE_LOADER = 'ARTICLE_FETCH_DISABLE_LOADER';

export const STORE_FID_ENABLE_LOADER = 'STORE_FID_ENABLE_LOADER';
export const STORE_FID_DISABLE_LOADER = 'STORE_FID_DISABLE_LOADER';

export const FETCH_BODY_REACTIONS_ENABLE_LOADER = 'FETCH_BODY_REACTIONS_ENABLE_LOADER';
export const FETCH_BODY_REACTIONS_DISABLE_LOADER = 'FETCH_BODY_REACTIONS_DISABLE_LOADER';

export const FETCH_SUBJECTS_ENABLE_LOADER = 'FETCH_SUBJECTS_ENABLE_LOADER';
export const FETCH_SUBJECTS_DISABLE_LOADER = 'FETCH_SUBJECTS_DISABLE_LOADER';

export const FETCH_SECONDARY_EMOTIONS_ENABLE_LOADER = 'FETCH_SECONDARY_EMOTIONS_ENABLE_LOADER';
export const FETCH_SECONDARY_EMOTIONS_DISABLE_LOADER = 'FETCH_SECONDARY_EMOTIONS_DISABLE_LOADER';

export const FETCH_FIDS_ENABLE_LOADER = 'FETCH_FIDS_ENABLE_LOADER';
export const FETCH_FIDS_DISABLE_LOADER = 'FETCH_FIDS_DISABLE_LOADER';

export const FETCH_FIDS_OF_DAY_ENABLE_LOADER = 'FETCH_FIDS_OF_DAY_ENABLE_LOADER';
export const FETCH_FIDS_OF_DAY_DISABLE_LOADER = 'FETCH_FIDS_OF_DAY_DISABLE_LOADER';

export const FETCH_PROFILE_ENABLE_LOADER = 'FETCH_PROFILE_ENABLE_LOADER';
export const FETCH_PROFILE_DISABLE_LOADER = 'FETCH_PROFILE_DISABLE_LOADER';

export const STORE_PROFILE_ENABLE_LOADER = 'STORE_PROFILE_ENABLE_LOADER';
export const STORE_PROFILE_DISABLE_LOADER = 'STORE_PROFILE_DISABLE_LOADER';

export const RESET_PASSWORD_ENABLE_LOADER = 'RESET_PASSWORD_ENABLE_LOADER';
export const RESET_PASSWORD_DISABLE_LOADER = 'RESET_PASSWORD_DISABLE_LOADER';

export const FETCH_SUBSCRIPTION_PLANS_ENABLE_LOADER = 'FETCH_SUBSCRIPTION_PLANS_ENABLE_LOADER';
export const FETCH_SUBSCRIPTION_PLANS_DISABLE_LOADER = 'FETCH_SUBSCRIPTION_PLANS_DISABLE_LOADER';

export const FETCH_USER_SUBSCRIPTION_ENABLE_LOADER = 'FETCH_USER_SUBSCRIPTION_ENABLE_LOADER';
export const FETCH_USER_SUBSCRIPTION_DISABLE_LOADER = 'FETCH_USER_SUBSCRIPTION_DISABLE_LOADER';

export const SEND_FIDBACK_REQUEST_ENABLE_LOADER = 'SEND_FIDBACK_REQUEST_ENABLE_LOADER';
export const SEND_FIDBACK_REQUEST_DISABLE_LOADER = 'SEND_FIDBACK_REQUEST_DISABLE_LOADER';

export const AUTOFIDBACKS_FETCH_ENABLE_LOADER = 'AUTOFIDBACKS_FETCH_ENABLE_LOADER';
export const AUTOFIDBACKS_FETCH_DISABLE_LOADER = 'AUTOFIDBACKS_FETCH_DISABLE_LOADER';

export const AUTOFIDBACK_FETCH_ENABLE_LOADER = 'AUTOFIDBACK_FETCH_ENABLE_LOADER';
export const AUTOFIDBACK_FETCH_DISABLE_LOADER = 'AUTOFIDBACK_FETCH_DISABLE_LOADER';

export const REGISTER_PUSH_NOTIFICATION_TOKEN_ENABLE_LOADER = 'REGISTER_PUSH_NOTIFICATION_TOKEN_ENABLE_LOADER';
export const REGISTER_PUSH_NOTIFICATION_TOKEN_DISABLE_LOADER = 'REGISTER_PUSH_NOTIFICATION_TOKEN_DISABLE_LOADER';

export const AUTOFIDBACK_NOTE_STORE_ENABLE_LOADER = 'AUTOFIDBACK_NOTE_STORE_ENABLE_LOADER';
export const AUTOFIDBACK_NOTE_STORE_DISABLE_LOADER = 'AUTOFIDBACK_NOTE_STORE_DISABLE_LOADER';

export const PERSONAL_FIDBACK_PROFILE_STORE_ENABLE_LOADER = 'PERSONAL_FIDBACK_PROFILE_STORE_ENABLE_LOADER';
export const PERSONAL_FIDBACK_PROFILE_STORE_DISABLE_LOADER = 'PERSONAL_FIDBACK_PROFILE_STORE_DISABLE_LOADER';

export const CHECK_USER_SUBSCRIPTION_ENABLE_LOADER = 'CHECK_USER_SUBSCRIPTION_ENABLE_LOADER';
export const CHECK_USER_SUBSCRIPTION_DISABLE_LOADER = 'CHECK_USER_SUBSCRIPTION_DISABLE_LOADER';

export const FETCH_PERSONAL_FIDBACK_LIST_ENABLE_LOADER = 'FETCH_PERSONAL_FIDBACK_LIST_ENABLE_LOADER';
export const FETCH_PERSONAL_FIDBACK_LIST_DISABLE_LOADER = 'FETCH_PERSONAL_FIDBACK_LIST_DISABLE_LOADER';

export const FETCH_PERSONAL_FIDBACK_MESSAGES_ENABLE_LOADER = 'FETCH_PERSONAL_FIDBACK_MESSAGES_ENABLE_LOADER';
export const FETCH_PERSONAL_FIDBACK_MESSAGES_DISABLE_LOADER = 'FETCH_PERSONAL_FIDBACK_MESSAGES_DISABLE_LOADER';

export const SEND_PERSONAL_FIDBACK_MESSAGE_ENABLE_LOADER = 'SEND_PERSONAL_FIDBACK_MESSAGE_ENABLE_LOADER';
export const SEND_PERSONAL_FIDBACK_MESSAGE_DISABLE_LOADER = 'SEND_PERSONAL_FIDBACK_MESSAGE_DISABLE_LOADER';

export const OPEN_SUBSCRIPTION_PLAN_ENABLE_LOADER = 'OPEN_SUBSCRIPTION_PLAN_ENABLE_LOADER';
export const OPEN_SUBSCRIPTION_PLAN_DISABLE_LOADER = 'OPEN_SUBSCRIPTION_PLAN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_UPDATE = 'USER_UPDATE';

// logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RESPONSE = 'LOGOUT_RESPONSE';

// registration
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_RESPONSE = 'REGISTRATION_RESPONSE';

// blog
export const ARTICLES_FETCH_REQUEST = 'ARTICLES_FETCH_REQUEST';
export const ARTICLES_FETCH_RESPONSE = 'ARTICLES_FETCH_RESPONSE';

export const ARTICLE_FETCH_REQUEST = 'ARTICLE_FETCH_REQUEST';
export const ARTICLE_FETCH_RESPONSE = 'ARTICLE_FETCH_RESPONSE';

// relaxation exercises
export const RELAXATION_EXERCISES_FETCH_REQUEST = 'RELAXATION_EXERCISES_FETCH_REQUEST';
export const RELAXATION_EXERCISES_FETCH_RESPONSE= 'RELAXATION_EXERCISES_FETCH_RESPONSE';

// lockdown mental health tips
export const LOCKDOWN_MENTAL_HEALTH_TIPS_FETCH_REQUEST = 'LOCKDOWN_MENTAL_HEALTH_TIPS_FETCH_REQUEST';
export const LOCKDOWN_MENTAL_HEALTH_TIPS_FETCH_RESPONSE= 'LOCKDOWN_MENTAL_HEALTH_TIPS_FETCH_RESPONSE';

// fid
export const STORE_FID_REQUEST = 'STORE_FID_REQUEST';
export const STORE_FID_RESPONSE = 'STORE_FID_RESPONSE';

// body reactions
export const FETCH_BODY_REACTIONS_REQUEST = 'FETCH_BODY_REACTIONS_REQUEST';
export const FETCH_BODY_REACTIONS_RESPONSE = 'FETCH_BODY_REACTIONS_RESPONSE';

// subjects
export const FETCH_SUBJECTS_REQUEST = 'FETCH_SUBJECTS_REQUEST';
export const FETCH_SUBJECTS_RESPONSE = 'FETCH_SUBJECTS_RESPONSE';

// secondary emotions
export const FETCH_SECONDARY_EMOTIONS_REQUEST = 'FETCH_SECONDARY_EMOTIONS_REQUEST';
export const FETCH_SECONDARY_EMOTIONS_RESPONSE = 'FETCH_SECONDARY_EMOTIONS_RESPONSE';

// calendar
export const FETCH_FIDS_REQUEST = 'FETCH_FIDS_REQUEST';
export const FETCH_FIDS_RESPONSE = 'FETCH_FIDS_RESPONSE';

// calendar
export const FETCH_FIDS_OF_DAY_REQUEST = 'FETCH_FIDS_OF_DAY_REQUEST';
export const FETCH_FIDS_OF_DAY_RESPONSE = 'FETCH_FIDS_OF_DAY_RESPONSE';

// profile
export const STORE_PROFILE_REQUEST = 'STORE_PROFILE_REQUEST';
export const STORE_PROFILE_RESPONSE = 'STORE_PROFILE_RESPONSE';

// reset password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_RESPONSE = 'RESET_PASSWORD_RESPONSE';

// fidback request
export const SEND_FIDBACK_REQUEST_REQUEST = 'SEND_FIDBACK_REQUEST_REQUEST';
export const SEND_FIDBACK_REQUEST_RESPONSE = 'SEND_FIDBACK_REQUEST_RESPONSE';

// subscription plans
export const FETCH_SUBSCRIPTION_PLANS_REQUEST = 'FETCH_SUBSCRIPTION_PLANS_REQUEST';
export const FETCH_SUBSCRIPTION_PLANS_RESPONSE = 'FETCH_SUBSCRIPTION_PLANS_RESPONSE';

// autofidbacks
export const AUTOFIDBACKS_FETCH_REQUEST ='AUTOFIDBACKS_FETCH_REQUEST';
export const AUTOFIDBACKS_FETCH_RESPONSE = 'AUTOFIDBACKS_FETCH_RESPONSE';

// autofidbacks
export const AUTOFIDBACK_FETCH_REQUEST ='AUTOFIDBACK_FETCH_REQUEST';
export const AUTOFIDBACK_FETCH_RESPONSE = 'AUTOFIDBACK_FETCH_RESPONSE';

// push notifications
export const REGISTER_PUSH_NOTIFICATION_TOKEN_REQUEST ='REGISTER_PUSH_NOTIFICATION_TOKEN_REQUEST';
export const REGISTER_PUSH_NOTIFICATION_TOKEN_RESPONSE = 'REGISTER_PUSH_NOTIFICATION_TOKEN_RESPONSE';

// push notifications
export const AUTOFIDBACK_NOTE_STORE_REQUEST ='AUTOFIDBACK_NOTE_STORE_REQUEST';
export const AUTOFIDBACK_NOTE_STORE_RESPONSE = 'AUTOFIDBACK_NOTE_STORE_RESPONSE';

// push notifications
export const PERSONAL_FIDBACK_PROFILE_STORE_REQUEST ='PERSONAL_FIDBACK_PROFILE_STORE_REQUEST';
export const PERSONAL_FIDBACK_PROFILE_STORE_RESPONSE = 'PERSONAL_FIDBACK_PROFILE_STORE_RESPONSE';

// Personal Fidback List
export const FETCH_PERSONAL_FIDBACK_LIST_REQUEST ='FETCH_PERSONAL_FIDBACK_LIST_REQUEST';
export const FETCH_PERSONAL_FIDBACK_LIST_RESPONSE = 'FETCH_PERSONAL_FIDBACK_LIST_RESPONSE';

// Personal Fidback Messages
export const FETCH_PERSONAL_FIDBACK_MESSAGES_REQUEST ='FETCH_PERSONAL_FIDBACK_MESSAGES_REQUEST';
export const FETCH_PERSONAL_FIDBACK_MESSAGES_RESPONSE = 'FETCH_PERSONAL_FIDBACK_MESSAGES_RESPONSE';

// Personal Fidback Messages
export const SEND_PERSONAL_FIDBACK_MESSAGE_REQUEST ='SEND_PERSONAL_FIDBACK_MESSAGE_REQUEST';
export const SEND_PERSONAL_FIDBACK_MESSAGE_RESPONSE = 'SEND_PERSONAL_FIDBACK_MESSAGE_RESPONSE';

// check user subscriptions
export const CHECK_USER_SUBSCRIPTION_REQUEST ='CHECK_USER_SUBSCRIPTION_REQUEST';
export const CHECK_USER_SUBSCRIPTION_RESPONSE = 'CHECK_USER_SUBSCRIPTION_RESPONSE';

// open subscription plan
export const OPEN_SUBSCRIPTION_PLAN_REQUEST ='OPEN_SUBSCRIPTION_PLAN_REQUEST';
export const OPEN_SUBSCRIPTION_PLAN_RESPONSE = 'OPEN_SUBSCRIPTION_PLAN_RESPONSE';
