/* App config for apis
 */
const ApiConstants = {
    BASE_URL: 'https://app.feelidentity.com/',
    LOGIN: 'api/authenticate',
    REGISTER: 'api/register',
    LOGOUT: 'api/logout',
    PROFILE: 'api/user/profile',
    BLOG: 'api/',
    BLOG_CATEGORY: 'api/blog-category/',
    RELAXATION_EXERCISES: 'api/relaxation-exercises',
    LOCKDOWN_MENTAL_HEALTH_TIPS: 'api/lockdown-mental-helth-tips',
    FID: 'api/fid/',
    BODY_REACTION: 'api/body-reaction/',
    SUBJECTS: 'api/subjects',
    PASSWORD_RESET: 'api/password-reset',
    IMAGE: 'api/image',
    SECONDARY_EMOTIONS: 'api/secondary-emotions',
    TEXT: 'api/text/',
    FIDBACK_REQUEST: 'api/fidback-request',
    USER_SUBSCRIPTION: 'api/check-user-subscription',
    SUBSCRIPTION_PLANS: 'api/subscription-plans',
    WEB_SUBSCRIPTION_PLANS: 'subscription-plans/',
    TERMS_OF_USE: 'text/terms_of_use',
    PRIVACY_POLICY: 'text/privacy_policy',
    PUSH_NOTIFICATION: 'api/push-notification',
    AUTOFIDBACK: 'api/autofidback',
    AUTOFIDBACK_NOTE:  'api/autofidbacknote',
    PERSONAL_FIDBACK:  'api/personal-fidbacks',
    PERSONAL_FIDBACK_MESSAGE:  'api/personal-fidback/response',
    PERSONAL_FIDBACK_PROFILE:  'api/personal-fidback-profile',
    ONE_TIME_LOGIN_TOKEN:  'api/one-time-login-token',
};

export default ApiConstants;
